version: "3.8"

services:
  web:
    build: ../../backend/
    volumes:
      - ../../backend:/app/
    environment:
      DJANGO_ADMIN_USERNAME: t2elzeth@gmail.com
      DJANGO_ADMIN_PASSWORD: admin12345
  nginx:
    build: ./nginx
    volumes:
      - ../../backend/staticfiles:/app/static
      - ../../backend/media:/app/media
    ports:
      - "8920:80"
    depends_on:
      - web
