version: "3.8"

services:
  web:
    build: .
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    environment:
      DJANGO_ADMIN_USERNAME: t2elzeth@gmail.com
      DJANGO_ADMIN_PASSWORD: admin12345

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}Nginx
    ports:
      - "8920:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/static
      - mediafiles:/app/media
    depends_on:
      - web

volumes:
  staticfiles:
    name: ${PROJECT_NAME}Staticfiles

  mediafiles:
    name: ${PROJECT_NAME}Mediafiles